### ISSUE TITLE
Markdown support checklist bug

### ISSUE THREAD

**Issue by fankangsong** [bordaigorl/sublime-evernote#114] opened 2015-10-12 07:46 UTC
checked one of list radios in Evernote, then sync to sublime text. the radio list has checked all of  them.

**Comment by bordaigorl** [comment] 2015-11-07 22:06
Could you please give more information? Can you reproduce the issue with a simple note you can copy in the issue? I need to see the contents of the note and the generated markdown to understand what's happening.

**Comment by Philiphlop** [comment] 2016-10-20 18:13
I had same issue which had what @fankangsong is mentioning, plus something else. Here is a screenshot of this across all 3 stages.

- Stage 1, create the note as shown within Evernote
- Stage 2, sync and then pull down into Sublime
- Stage 3, edit within Sublime, leaving checklist untouched, upload and then check in Evernote

![evernotesublime](https://cloud.githubusercontent.com/assets/22427598/19571995/5993740e-96f8-11e6-8461-b33423fdcb5f.png)

As you can see the sublime shot second set of checkboxes are filled with an X "[x]" despite not being checked within Evernote. The first set shows that they come through with the tag false (and true when checked from previous tests). 

A second issue arises with the first block down to the structuring of the elements. 
This is repeatable for myself.

# System Information
* Window 10
* Evernote 6.3.3.3502
* Sublime build 3126

**Comment by bordaigorl** [comment] 2016-10-23 11:47
Hi, thanks for reporting this.
Right now I am not able to reproduce the issue on OSX.
To help me debug this, could you set the `debug` setting to `true` in the Evernote settings in Sublime, then repeat the tests: in the console you should now see the full contents of the note in HTML too. If you could post that it would help: it seems that different Evernote clients use slightly different HTML encodings of elements and the parser in the ST plugin has not been thoroughly tested against all versions of the clients.
(Maybe one can also say that the Evernote format is just too under-specified).

Incidentally, I fixed a small bug that was introducing the unnecessary `<div style=";">`, the fix will be included in the next release.

**Comment by Philiphlop** [comment] 2016-10-23 18:20
Hey sure no problem.

Here is 4 tests carried out, with variations on the workflow to try expose the issue. My initial thoughts from this are that there is a difference in the checked="xyz" flag usage, Sublime does not create and presumably recognise the checked="false" flag, presuming non checked="true" to be false. Whereas Evernote client is declaring explicitly checked="false" for unchecked items.

# Test 1
## Setup
1. Created new note in Evernote client with simple set of tasks, sync to Evernote servers.
  * ![cap1](https://cloud.githubusercontent.com/assets/22427598/19628271/0ea61b3e-9952-11e6-82bf-6384956c28b9.PNG)
2. Pull note to Sublime using search

## Result
Result is fully checked boxes, so failed test. 
![cap2](https://cloud.githubusercontent.com/assets/22427598/19628289/5b4011c0-9952-11e6-9d0f-76631e3ad039.PNG)

## Log
```
Evernote: Using cached notebooks list
Evernote: Using cached notebooks list
Evernote: <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">



<en-note><ul><li><en-todo checked="false"/>Task 1</li><li><en-todo checked="false"/>Task 2
<ul><li><en-todo checked="false"/>Task 2.1</li><li><en-todo checked="false"/>Task 2.2</li></ul></li><li><en-todo checked="false"/>Task 3</li><li><en-todo checked="false"/>Task 4</li></ul><div><br/></div><div><br/></div><div><br/></div></en-note>
Evernote: 620fbd36-278a-480d-acd1-e6a8ca9cb450
Evernote: Conversion ok
```

# Test 2
## Setup
1. Take result of Test 1 in Sublime and uncheck some items
  * ![cap1](https://cloud.githubusercontent.com/assets/22427598/19628306/a560701a-9952-11e6-8eed-ab33d0b1d629.PNG)
2. Push/save to Evernote servers from Sublime
3. Pull in Evernote client

## Result
Result is partial checked boxes, so passed test. 
![cap4](https://cloud.githubusercontent.com/assets/22427598/19628322/fd8741ce-9952-11e6-94cb-ec22fefced0b.PNG)

## Log
```
>>> 
Evernote: <ul>
<li style="list-style-type: none;"><en-todo/>Task 1</li>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2 
<ul>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2.1</li>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2.2</li>
</ul></li>
<li style="list-style-type: none;"><en-todo/>Task 3</li>
<li style="list-style-type: none;"><en-todo/>Task 4</li>
</ul>

Evernote: []
Evernote: Using cached notebooks list
```

# Test 3
## Setup
1. Take result of Test 2
2. Close Sublime tab without save (no changes made), close sublime, check killed in Task Manager
3. Open Sublime
4. Pull note from Evernote servers to Sublime with search

## Result
Result is partial checked boxes, so passed test. 
![cap5](https://cloud.githubusercontent.com/assets/22427598/19628346/71aeb42e-9953-11e6-96cb-438d08bee781.PNG)

## Log
```
Evernote: Using cached notebooks list
Evernote: Using cached notebooks list
Evernote: <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note style=";">
<!-- Sublime:LS0tCnRpdGxlOiBBY3Rpb24gVGFza3MKdGFnczogW10Kbm90ZWJvb2s6ICFJbmJveAotLS0KCiAgKiBbIF0gVGFzayAxCiAgKiBbeF0gVGFzayAyIAogICAgKiBbeF0gVGFzayAyLjEKICAgICogW3hdIFRhc2sgMi4yCiAgKiBbIF0gVGFzayAzCiAgKiBbIF0gVGFzayA0CgogIAoKCiAgCgoKICAKCg==-->
<ul>
<li style="list-style-type: none;"><en-todo/>Task 1</li>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2 
<ul>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2.1</li>
<li style="list-style-type: none;"><en-todo checked="true"/>Task 2.2</li>
</ul></li>
<li style="list-style-type: none;"><en-todo/>Task 3</li>
<li style="list-style-type: none;"><en-todo/>Task 4</li>
</ul>
```

# Test 4
## Setup
1. Created new note in Evernote client with simple set of tasks, sync to Evernote servers.
  * Difference to Test 1, is that this has some partial checked, as that has succeeded in interim tests.
  * ![cap6](https://cloud.githubusercontent.com/assets/22427598/19628381/6025f13a-9954-11e6-8f12-94c9fd2e32dd.PNG)
2. Pull note to Sublime using search

## Result
Result is fully checked boxes, so failed test. 
![cap7](https://cloud.githubusercontent.com/assets/22427598/19628386/931c6ac4-9954-11e6-828c-603809b9f066.PNG)

## Log
```
Evernote: Using cached notebooks list
Evernote: Using cached notebooks list
Evernote: <?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">



<en-note><ul><li><en-todo checked="true"/>Task A</li><li><en-todo checked="false"/>Task B
<ul><li><en-todo checked="true"/>Task X</li><li><en-todo checked="false"/>Task Y</li></ul></li><li><en-todo checked="true"/>Task C</li><li><en-todo checked="false"/>Task D</li></ul></en-note>
Evernote: 88e0eb18-9000-4e58-ad1b-b10e7f343db6
Evernote: Conversion ok
```

**Comment by bordaigorl** [comment] 2016-10-23 19:48
Thanks a lot.
Yes, it was indeed an improper parsing of the `checked` attribute.
It will be fixed in next release.

**Closed** 2020-06-05 15:22 UTC
Labels: unconfirmed
